### ISSUE TITLE
How do I use a project level config.xml to configure cflint-syntastic?

### ISSUE THREAD

**Issue by jontrainor** [cflint/cflint-syntastic#3]
For other syntastic linters I can add the config file the linter expects into the top level of the project directory and the plugin will use it. Is this possible with cflint?

Thanks!!

**Comment by displague** [comment]
Which other linter? (I'll check if they are using some special syntastic magic that we can borrow)

**Comment by jphustman** [comment]
Correct me if I am wrong, but I believe jontrainor is talking about something similar to what a .jslintrc file does that you can put at the root of your project.  http://carlsenindex.dk/jslint-now-supports-.jslintrc/ (using jslint as an example)

**Comment by jontrainor** [comment]
Thank you Jeremey! That's exactly what i was talking about, I just didn't
get a chance to respond yesterday.

**Comment by jphustman** [comment]
I'll see if I can figure something out over the weekend

**Comment by jphustman** [comment]
Could be fixed when cflint/CFLint#95 is implemented.

**Comment by jontrainor** [comment]
Thanks for the help!
